import type { Metadata } from "next";
import Navbar from "@/components/Navigation/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import {AppWindowProvider} from "@/context/AppWindowContext";
import {firaMono} from "@/lib/fonts";
import "./globals.css";
import clsx from "clsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
            firaMono.className,
            `${geistSans.variable} ${geistMono.variable}`,
            // "bg-gradient-to-t from-blue-500 to-45% to-gray-800 h-screen antialiased"
        )}
      >
        <AppWindowProvider>
            <Navbar/>
            {children}
        </AppWindowProvider>
      </body>
    </html>
  );
}
